export type ProjectStatus =
  | 'Completed'
  | 'Under Development'
  | 'Planned'
  | 'Operations & Maintenance'
  | 'Under Construction'
  | 'EPC Completed - Operations & Maintenance Ongoing';

export type BusinessAreaType = 'solar-pv' | 'bess' | 'transmission-distribution' | 'hybrid-energy' | 'biogas-biomethane' | 'waste-management';

export interface Project {
  id?: string; // Optional because it's generated by Firestore
  title: string;
  sub_title?: string;
  detailProjectName?: string;
  detailPageTechnology?: string;
  order?: number;
  slug?: string;

  // Categorization
  country: string;
  region: string; // West Africa, East Africa, etc.
  businessArea?: BusinessAreaType; // e.g., "solar-pv", "bess", etc.

  // Technical Specs
  capacity?: string; // e.g., "1.2 MWp"
  technology?: string; // e.g., "Ground-Mounted Solar PV"
  client?: string; // e.g., "Ministry of Health"
  status: ProjectStatus;
  planned?: boolean;
  completionYear?: string;

  // Content
  location: string; // e.g., "Santo Amaro, São Tomé"
  description: string; // HTML or Markdown
  beneficiary?: string;
  financing?: string;

  // Media
  imageUrl?: string; // Cover image URL
  galleryUrls?: string[]; // Additional images

  // Metadata
  createdAt?: any; // Firestore Timestamp
  updatedAt?: any;
  deletedAt?: string | null;
}

export interface ProjectCountry {
  name: string;
  projects: Project[];
}

export interface ProjectRegion {
  id: string;
  name: string;
  countries: ProjectCountry[];
}
