export type ProjectStatus = 'Completed' | 'Under Development' | 'Planned' | 'Operation & Maintenance';

export interface Project {
    id?: string; // Optional because it's generated by Firestore
    title: string;
    slug?: string;

    // Categorization
    country: string;
    region: string; // West Africa, East Africa, etc.

    // Technical Specs
    capacity?: string; // e.g., "1.2 MWp"
    technology?: string; // e.g., "Ground-Mounted Solar PV"
    status: ProjectStatus;

    // Content
    location: string; // e.g., "Santo Amaro, São Tomé"
    description: string; // HTML or Markdown
    beneficiary?: string;
    financing?: string;

    // Media
    imageUrl?: string; // Cover image URL
    galleryUrls?: string[]; // Additional images

    // Metadata
    createdAt?: any; // Firestore Timestamp
    updatedAt?: any;
}

export interface ProjectCountry {
    name: string;
    projects: Project[];
}

export interface ProjectRegion {
    id: string;
    name: string;
    countries: ProjectCountry[];
}
